#!/bin/bash

network=$(networksetup -getairportnetwork en1 | cut -d ' ' -f 4);
# echo "$network";
#security find-generic-password -ga $network | grep "^password";
security find-generic-password -ga $network | grep "^password"; 


