#!/bin/bash

# a simple script to print out the password of the network you are currently connected to

network=$(networksetup -getairportnetwork en1 | cut -d ' ' -f 4);
# echo "$network";
#security find-generic-password -ga $network | grep "^password";
security find-generic-password -ga $network | grep "^password"; 


